services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
      no_cache: false
      args:
        DATA_URL: ''
    image: cars
    container_name: cars
    ports:
      - 3000:3000
    user: nginx
    read_only: true
    privileged: false
    tmpfs:
      - /tmp:rw
    # volumes:
    #   - /tmp