version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENV_FILE: .env
    image: trafi
    container_name: trafi
    ports:
      - 3000:3000
    read_only: false