services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
      no_cache: false
      args:
        DATA_URL: ''
        PORT: 3000
    depends_on:
      server:
        condition: service_started
        restart: true
    image: cars
    container_name: cars
    ports:
      - 3000:3000
    user: nginx
    read_only: true
    privileged: false
    tmpfs:
      - /tmp:rw
  server:
    image: python:3.13-alpine
    container_name: cars-server
    volumes:
      - ./util:/scripts
      - ./data:/data
    ports:
      - 8000:8000
    read_only: true
    privileged: false
    tmpfs:
      - /tmp:rw
    command: ["python", "/scripts/http_server.py"]
  tests:
    build:
      context: .
      dockerfile: ./util/Dockerfile
      no_cache: false
    container_name: cars-tests
    read_only: false
    privileged: true
    command: ["npm", "run", "playwright:update"]