block-list-secret-scan: []
branch: master
custom-tool-name: Checkov
directory:
  - .
evaluate-variables: true
external-modules-download-path: .external_modules
mask: []
secrets-history-timeout: 12h
secrets-scan-file-type: []
skip-check:
  - CKV_AWS_18
  - CKV_AWS_21
  - CKV_AWS_26
  - CKV_AWS_51
  - CKV_AWS_68
  - CKV_AWS_86
  - CKV_AWS_116
  - CKV_AWS_117
  - CKV_AWS_136
  - CKV_AWS_158
  - CKV_AWS_163
  - CKV_AWS_173
  - CKV_AWS_174
summary-position: top
