Parameters:
  AllowedCountries:
    Description: List of allowed distribution countries
    Type: CommaDelimitedList
    Default: ""
  BucketName:
    Description: Target bucket name
    Type: String
  OriginAccessControlId:
    Description: Target origin access control id
    Type: String

Conditions:
  IsEmptyCountryList:
    Fn::Equals: [!Join [",", !Ref AllowedCountries], ""]

Resources:
  CachePolicy:
    Type: "AWS::CloudFront::CachePolicy"
    Properties:
      CachePolicyConfig:
        Name: !Sub "${AWS::StackName}-cache-policy"
        DefaultTTL: 86400
        MaxTTL: 31536000
        MinTTL: 0
        ParametersInCacheKeyAndForwardedToOrigin:
          QueryStringsConfig:
            QueryStringBehavior: "none"
          HeadersConfig:
            HeaderBehavior: "none"
          CookiesConfig:
            CookieBehavior: "none"
          EnableAcceptEncodingBrotli: true
          EnableAcceptEncodingGzip: true

  CloudFrontDistribution:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        Origins:
          - Id: !Sub "${AWS::StackName}-origin"
            DomainName: !Sub "${BucketName}.s3.amazonaws.com"
            OriginAccessControlId: !Ref OriginAccessControlId
            S3OriginConfig: {}
        Enabled: true
        PriceClass: PriceClass_All
        HttpVersion: http2and3
        DefaultCacheBehavior:
          TargetOriginId: !Sub "${AWS::StackName}-origin"
          ViewerProtocolPolicy: redirect-to-https
          Compress: true
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          CachePolicyId: !Ref CachePolicy
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
        DefaultRootObject: "data.json"
        Restrictions:
          GeoRestriction:
            RestrictionType: !If
              - IsEmptyCountryList
              - none
              - whitelist
            Locations: !If
              - IsEmptyCountryList
              - !Ref "AWS::NoValue"
              - !Ref AllowedCountries

  S3BucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref BucketName
      PolicyDocument:
        Version: "2012-10-17"
        Id: "CloudfrontBucketPolicy"
        Statement:
          - Effect: Allow
            Principal:
              Service: "cloudfront.amazonaws.com"
            Action: "s3:GetObject"
            Resource: !Sub "arn:aws:s3:::${BucketName}/*"
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}"

Outputs:
  CloudFrontDistributionDomainName:
    Description: Domain name of the CloudFront distribution
    Value: !GetAtt CloudFrontDistribution.DomainName
