name: deploy
on:
  push:
    branches:
      - main
    paths:
      - "app/src/**"
      - "app/vite.config.ts"
      - "app/tsconfig.json"
      - "app/package*.json"
      - ".github/workflows/deploy.yml"
  workflow_dispatch:
env:
  NO_UPDATE_NOTIFIER: true
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Install dependencies
        run: npm ci
        working-directory: ./app
      - name: Audit
        run: npm run audit
        working-directory: ./app
      - name: Build
        run: npm run build
        env:
          VITE_DATA_URL: ${{ vars.DATA_URL }}
        working-directory: ./app
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE }}
      - name: Add DATA_URL
        run: sed -i "s|__DATA_URL__|${{ vars.DATA_URL }}|g" ./dist/insert-links.js
        working-directory: ./app
      - name: Upload to S3
        run: |
          aws s3 sync dist s3://${{ secrets.APP_BUCKET }} --delete
        working-directory: ./app
      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.APP_DISTRIBUTION }} --paths "/*"
