name: deploy
on:
  push:
    branches:
      - main
    paths:
      - "app/src/**"
      - "app/nginx/**"
      - "app/vite.config.ts"
      - "app/tsconfig.json"
      - "app/package*.json"
      - "app/Dockerfile"
      - ".github/workflows/deploy.yml"
  workflow_dispatch:
env:
  NO_UPDATE_NOTIFIER: true
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  scan:
    uses: ./.github/workflows/scan.yml
    secrets: inherit
    with:
      severities: critical
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Install dependencies
        run: npm ci
        working-directory: ./app
      - name: Audit
        run: npm run audit
        working-directory: ./app
  deploy:
    runs-on: ubuntu-latest
    needs:
      - scan
      - audit
    steps:
      - name: Deploy
        run: curl "$DEPLOY_URL"
        env:
          DEPLOY_URL: ${{ secrets.DEPLOY_URL }}
