name: deploy
on:
  push:
    branches:
      - main
    paths:
      - "app/**"
      - "config/**"
      - "nginx/**"
      - "package*.json"
      - "Dockerfile"
      - "index.html"
      - "!.github/**"
      - ".github/workflows/deploy.yaml"
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: true
      - name: Build
        uses: docker/build-push-action@v6
        with:
          push: false
      - name: Deploy
        run: curl "$DEPLOY_URL"
        env:
          DEPLOY_URL: ${{ secrets.DEPLOY_URL }}
