name: deploy
on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "nginx/**"
      - "config/**"
      - "package*.json"
      - ".env.*"
      - "Dockerfile"
      - ".github/workflows/deploy.yml"
  workflow_dispatch:
jobs:
  scan:
    uses: ./.github/workflows/scan.yml
    secrets: inherit
    with:
      severities: critical
  deploy:
    runs-on: ubuntu-latest
    needs: scan
    steps:
      - name: Deploy
        run: curl "$DEPLOY_URL"
        env:
          DEPLOY_URL: ${{ secrets.DEPLOY_URL }}
