name: lighthouse
on:
  workflow_dispatch:
    inputs:
      url:
        description: "URL to audit"
        required: true
        default: "https://d1k2s1zvf9a8w8.cloudfront.net/"
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
      - name: Run audit
        id: lighthouse
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: ${{ inputs.url }}
          runs: 3
          uploadArtifacts: false
          temporaryPublicStorage: true
      - name: Report
        run: |
          LINKS=$(echo '${{ steps.lighthouse.outputs.links }}' | jq -r --arg url "$URL" '.[$url]')
          echo "[Results]($LINKS)" >> $GITHUB_STEP_SUMMARY
        env:
          URL: ${{ inputs.URL }}
