name: scan
on:
  pull_request:
    branches:
      - main
    paths:
      - "app/Dockerfile"
      - ".github/workflows/scan.yml"
  workflow_call:
    inputs:
      severities:
        description: "Comma-separated list of severities to scan for: critical, high, medium, low, unspecified"
        required: true
        type: string
        default: critical,high
  workflow_dispatch:
    inputs:
      severities:
        description: "Comma-separated list of severities to scan for: critical, high, medium, low, unspecified"
        required: true
        type: string
        default: critical,high
jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    env:
      IMAGE_TAG: cars-data:latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: true
      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: ./app
          push: false
          load: true
          pull: false
          no-cache: false
          tags: ${{ env.IMAGE_TAG }}
        env:
          DOCKER_BUILD_SUMMARY: false
          DOCKER_BUILD_RECORD_UPLOAD: false
      - name: Scan
        uses: docker/scout-action@v1
        with:
          command: cves,recommendations
          image: local://${{ env.IMAGE_TAG }}
          only-severities: ${{ inputs.severities || 'critical,high' }}
          only-fixed: true
          summary: true
          format: json
          exit-code: true
