name: scout
on:
  workflow_dispatch:
    inputs:
      severities:
        description: "Comma-separated list of severities to scan for: critical, high, medium, low, unspecified"
        required: true
        type: string
        default: critical,high
  schedule:
    - cron: "0 18 * * 3"
jobs:
  scan:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - repository: ${{ vars.DATA_LAMBDA_IMAGE_REPOSITORY }}
            tag: ${{ vars.DATA_LAMBDA_IMAGE_TAG }}
          - repository: ${{ vars.LAMBDA_IMAGE_REPOSITORY }}
            tag: ${{ vars.LAMBDA_IMAGE_TAG }}
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4.1.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0
      - name: Login to Docker Hub
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: true
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@254c19bd240aabef8777f48595e9d2d7b972184b # v6.2.1
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE }}
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@d539f0932e70871a027e9d5a9d8fc38589180a64 # v2.1.6
      - name: Scan image CVEs and recommendations
        uses: docker/scout-action@7520205ff60037fdc436b40b6a1d1e55a839ec2d # v1.22.0
        with:
          command: cves,recommendations
          image: "${{ matrix.image.repository }}:${{ matrix.image.tag }}"
          only-severities: ${{ inputs.severities || 'critical,high' }}
          only-fixed: true
          summary: true
          format: json
          exit-code: true
