name: scout
on:
  workflow_dispatch:
    inputs:
      severities:
        description: "Comma-separated list of severities to scan for: critical, high, medium, low, unspecified"
        required: true
        type: string
        default: critical,high
  schedule:
    - cron: "0 18 * * 3"
jobs:
  scan:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - repository: ${{ vars.DATA_LAMBDA_IMAGE_REPOSITORY }}
            tag: ${{ vars.DATA_LAMBDA_IMAGE_TAG }}
          - repository: ${{ vars.LAMBDA_IMAGE_REPOSITORY }}
            tag: ${{ vars.LAMBDA_IMAGE_TAG }}
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@1f40c72289eff860ee54a304f1438e3cff362e0a # v4.3.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@37fe631027851001ddb9b187196cc803df7f5f0e # v4.3.0
      - name: Login to Docker Hub
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: true
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@cbe3b392738ccf3f987d68400dafcf4b0624a56c # v6.2.4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE }}
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@03f1aad4c6c7ffd436567f42f9384779290529bd # v2.1.7
      - name: Scan image CVEs and recommendations
        uses: docker/scout-action@7c6b6c3f7844478ace1ffd4e7aef649053d1f87d # v1.24.0
        with:
          command: cves,recommendations
          image: "${{ matrix.image.repository }}:${{ matrix.image.tag }}"
          only-severities: ${{ inputs.severities || 'critical,high' }}
          only-fixed: true
          summary: true
          format: json
          exit-code: true
